---
- name: "configure: Install python-gitlab dependency"
  pip:
    name: "python-gitlab<1.13"

- name: "configure: Register building runners using command module"
  # NOTE: gitlab_runner does not seem to fit with this setup
  #       as python-gitlab is quite outdated
  # NOTE: Runners registered this way will only fetch untagged jobs
  command: |
    gitlab-runner register --non-interactive --url "http://{{ gitlab_addr }}"
    --registration-token "{{ gitlab_runner_register_token }}"
    --clone-url "http://{{ gitlab_addr }}"
    --executor shell
    --description "Docker machine node {{ inventory_hostname }}"

- name: "configure: Add gitlab-runner to docker group"
  user:
    append: true
    name: gitlab-runner
    groups:
      - docker

- name: "configure: Execute post-inst script"
  shell: "{{ gitlab_runner_post_inst_script }}"
  # args:
  # creates: "{{ gitlab_runner_config_file }}"

- name: "configure: Register the swarm update runner"
  # NOTE: gitlab_runner does not seem to fit with this setup
  #       as python-gitlab is quite outdated
  command: |
    gitlab-runner register --non-interactive --url "http://{{ gitlab_addr }}"
    --registration-token "{{ gitlab_runner_register_token }}"
    --clone-url "http://{{ gitlab_addr }}"
    --executor shell --tag-list deploy
    --description "Docker swarm deployer ({{ inventory_hostname }})"
  when: "'docker_swarm_manager' in group_names"

- name: "configure: Enable prometheus metrics"
  lineinfile:
    path: "{{ gitlab_runner_config_file }}"
    line: 'listen_address = "{{ gitlab_runner_metrics_address }}"'
    insertbefore: BOF
  notify:
    - restart-runners
