---
- name: "install: Fetch installation script to local host"
  delegate_to: localhost
  get_url:
    url: "{{ gitlab_runner_package_script_url }}"
    dest: "{{ gitlab_runner_tmp_script_location }}"

- name: "install: Run the package configuration script"
  script: "{{ gitlab_runner_tmp_script_location }}"
  args:
    creates: "{{ gitlab_apt_list_file }}"

- name: "install: Ensure apt file exist"
  stat:
    path: "{{ gitlab_apt_pref_file }}"
  register: apt_file

- name: "install: Ensure apt priorisation file exists"
  file:
    path: "{{ gitlab_apt_pref_file }}"
    state: touch
  when: "apt_file is defined and not apt_file.stat.exists"

- name: "install: Prioritize Gitlab's repositories over Debian's"
  blockinfile:
    path: "{{ gitlab_apt_pref_file }}"
    block: |
      Explanation: Prefer GitLab provided packages over the Debian native ones
      Package: gitlab-runner
      Pin: origin packages.gitlab.com
      Pin-Priority: 1001

- name: "install: Install the runner"
  apt:
    update_cache: true
    name:
      - "gitlab-runner"

- name: "configure: Install python dependency"
  pip:
    name: "python-gitlab<1.13"

- name: "configure: Register the runner"
  gitlab_runner:
    state: present
    active: true
    registration_token: "{{ gitlab_runner_register_token }}"
    # TODO: disable run_untagged and add tag_list
    # tag_list: ['docker']
    run_untagged: true
    api_url: "http://{{ gitlab_addr }}"
    api_token: "{{ gitlab_token }}"
    description: "Docker machine node {{ inventory_hostname }}"
    locked: false
    # when: "inventory_hostname == 'vm3'"
  when: false

- name: "configure: Register the runner using command"
  # TODO: Use the previous gitlab_runner task instead of command
  command: |
    gitlab-runner register --non-interactive --url "http://{{ gitlab_addr }}"
    --registration-token "{{ gitlab_runner_register_token }}"
    --executor shell
    --description "Docker machine node {{ inventory_hostname }}"

- name: "configure: Add gitlab-runner to docker group"
  user:
    append: true
    name: gitlab-runner
    groups:
      - docker

- name: "configure: Execute post-inst script"
  shell: "{{ gitlab_runner_post_inst_script }}"
  # args:
  # creates: "{{ gitlab_runner_config_file }}"


- name: "configure: Ensure the runner has the correct repository address"
  lineinfile:
    insertafter: "[[runners]]"
    line: "  clone_url = \"http://{{ gitlab_addr }}\""
    path: "/etc/gitlab-runner/config.toml"
  when: false
  # when: "inventory_hostname == 'vm3'"
