---
gitlab_interface: "{{ ansible_default_ipv4['interface'] }}"
gitlab_addr: "{{ hostvars[inventory_hostname]['ansible_' + gitlab_interface]['ipv4']['address']  }}"
gitlab_password: "SamplePassword"
gitlab_install: "yes"
gitlab_setup_users: "yes"
gitlab_host: "vm3"
