---
# partition customisation
glusterfs_data_size: 3G
glusterfs_part_directory: "/opt/gluster"
glusterfs_partition: "{{ glusterfs_part_directory }}/data"

# glusterfs global configuration
glusterfs_working_directory: "/mnt/glusterfs"
glusterfs_base_mountpoint: "/mnt/shared"

# glusterfs bricks
glusterfs_shared_monitoring: "{{ glusterfs_working_directory }}/monitoring"
glusterfs_mounted_monitoring: "{{ glusterfs_base_mountpoint }}/monitoring"
glusterfs_shared_registry: "{{ glusterfs_working_directory }}/registry"
glusterfs_mounted_registry: "{{ glusterfs_base_mountpoint }}/registry"

# glusterfs applicative bricks
glusterfs_shared_production: "{{ glusterfs_working_directory }}/production"
glusterfs_mounted_production: "{{ glusterfs_base_mountpoint }}/production"
glusterfs_shared_beta: "{{ glusterfs_working_directory }}/beta"
glusterfs_mounted_beta: "{{ glusterfs_base_mountpoint }}/beta"

# glusterfs peers
glusterfs_peer_a: 172.16.228.52
glusterfs_peer_b: 172.16.228.47
glusterfs_peer_c: 172.16.228.42

# first probing host
glusterfs_single: vm3
