"""empty message

Revision ID: 7bdd679c116c
Revises: 
Create Date: 2020-07-08 20:13:47.161512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bdd679c116c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option',
    sa.Column('id', sa.Integer(), unique=True, nullable=False),
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.drop_table('option')
    # ### end Alembic commands ###
