---
- name: "build: Create temporary directories for building {{ item.name }}"
  file:
    path: "/tmp/{{ item.name }}"
    state: directory
    recurse: true

- name: "build: Copy templates related to {{ item.name }} to remote host"
  template:
    src: "{{ item.name }}.j2"
    dest: "/tmp/{{ item.name }}/Dockerfile"

- name: "build: Build image for {{ item.name }}"
  docker_image:
    source: build
    build:
      path: "/tmp/{{ item.name }}"
      rm: true
    force_source: true
    name: "{{ registry_url }}/{{ item.name }}"
    tag: "{{ item.tag | default('latest') }}"
    repository: "{{ registry_url }}/{{ item.name }}"
    push: true
    force_tag: true
    state: present

- name: "build: Update the registry for image {{ registry_url }}/{{ item.name }}"
  docker_image:
    source: local
    name: "{{ registry_url }}/{{ item.name }}"
    push: true
    tag: "{{ item.tag | default('latest') }}"
    repository: "{{ registry_url }}/{{ item.name }}"
