---
- name: "build: Create temporary directories"
  file:
    path: "/tmp/{{ item }}"
    state: directory
    recurse: true

- name: "build: Copy templates to remote host"
  template:
    src: "{{ item }}.j2"
    dest: "/tmp/{{ item }}/Dockerfile"

- name: "build: Build images"
  docker_image:
    source: build
    build:
      path: "/tmp/{{ item }}"
      rm: true
      pull: true
    force_source: true
    name: "{{ item }}"
    push: true
    repository: "{{ registry_url }}/{{ item }}"
    tag: "latest"
